# Generated by Django 3.1.3 on 2024-07-04 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ev3', '0002_auto_20240703_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
